# https://starship.rs/config

[aws]
symbol = " "
disabled = true

[docker]
symbol = " "

[git_branch]
symbol = " "

[git_status]
# Extremely slow on massive monorepos.
disabled = true

[golang]
symbol = " "

[kubernetes]
disabled = false

[nodejs]
symbol = " "

[package]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

